### ISSUE TITLE
Question about INT4 weight only GEMM

### ISSUE THREAD

**Issue by Hongbosherlock** [tlc-pack/cutlass_fpA_intB_gemm#12]
Thank you for your excellent work.

May I ask if this project fully supports int4 weight-only quantized inference, such as AWQ's group-wise int4 quantization?

I've seen some features related to int4 
https://github.com/tlc-pack/cutlass_fpA_intB_gemm/blob/ed951b046f89ddfd990af8d2482e3350bda2fec6/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h#L112

https://github.com/tlc-pack/cutlass_fpA_intB_gemm/blob/ed951b046f89ddfd990af8d2482e3350bda2fec6/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm.h#L29

 but I'm not sure how to use them specifically.

**Comment by masahi** [comment]
This codebase was extracted from the FasterTransformer repo as described in the README. If you don't know how the FasterTransformer kernel is meant to be used, you are not ready to benefit from this codebase.
