### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by MingZwhy** [tlc-pack/cutlass_fpA_intB_gemm#22]
Would you plan to provide any test example of this kernel in the future which will be very helpful?
I have observed that some recent SOTA work like GPTQ and AWQ have used 4/3 bit weight-only quantization, so I wonder if I can use the  kernel in this repo to do 4bit weight-only quantization.

**Comment by masahi** [comment]
No. This repo was created for use in TVM, you can look at how TVM uses it.
