### ISSUE TITLE
How to run fp16_int8 gemm?

### ISSUE THREAD

**Issue by hld1919** [tlc-pack/cutlass_fpA_intB_gemm#29]
Is there an example to run fp16_int8 gemm? It is better that it can be used by pytorch.

**Comment by vinx13** [comment]
this repo has been used by tvm and mlc-llm, here is a high-level wrapper https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_llm/op/ft_gemm.py#L10, you can use these DLTensor interface https://github.com/tlc-pack/cutlass_fpA_intB_gemm/blob/main/tvm_binding/tvm_binding.cu#L37 for PyTorch.

there are also e2e usages in fastertransformer / tensorrt-llm
