### ISSUE TITLE
compute result problem

### ISSUE THREAD

**Issue by SidaZh** [tlc-pack/cutlass_fpA_intB_gemm#5]
This work is awesome, and I hope to ask for more details about using. Have you tested the accuracy or are there any test cases, because I don't know if I use this correctly.  Below is my wrapper for `gemm_fp16_int_bias_act` . I get weird result such as nan but the torch output is correct in the same case. 

```
void fpA_intB_gemm_forward_cuda(torch::Tensor &input,
                                torch::Tensor &weight,
                                torch::Tensor &scale,
                                torch::Tensor &output,
                                int m, int n, int k)
{
    c10::cuda::CUDAGuard device_guard(input.device());
    const fastertransformer::half *input_ptr = reinterpret_cast<fastertransformer::half *>(input.data_ptr());
    const uint8_t *weight_ptr = reinterpret_cast<const uint8_t *>(weight.data_ptr());
    const fastertransformer::half *scale_ptr = reinterpret_cast<fastertransformer::half *>(scale.data_ptr());
    fastertransformer::half *output_ptr = reinterpret_cast<fastertransformer::half *>(output.data_ptr());

    fastertransformer::gemm_fp16_int_bias_act(
        input_ptr,
        weight_ptr,
        scale_ptr,
        nullptr,
        output_ptr,
        std::nullopt,
        m, n, k,
        0,
        nullptr,
        0,
        0);
}
```

**Comment by masahi** [comment]
Have you studied how to prepare weight and scale tensors to use this lib?

**Comment by SidaZh** [comment]
I get int8 weight and float16 scale from huggingface LLM int8（https://github.com/TimDettmers/bitsandbytes）, input shape is (M, K), weight shape is (K, N), scale shape is (,N), but I have no idea about how to preprocess before use this lib.

**Comment by masahi** [comment]
Then you are not ready to use this lib. You need to spend a bit of time reading the original source code, such as https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/kernels/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm.h#L32-L35 and https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/kernels/cutlass_kernels/cutlass_preprocessors.cc to understand how to use this lib.

**Comment by NetEase-FuXi** [comment]
Thanks a lot! I will read this.

**Comment by SidaZh** [comment]
Thanks a lot! I will read this.
